osx_image: xcode12.4
language: objective-c
before_install:
  - gem install cocoapods
  - gem install xcpretty -N
  - cd Example ; pod install ; cd ..
script:
  - set -o pipefail
  - travis_retry xcodebuild test -workspace Example/TinySwift.xcworkspace -scheme TinySwift-Example -destination 'platform=iOS Simulator,name=iPhone 8' | xcpretty -c
  - pod lib lint --allow-warnings
after_success:
  - test $TRAVIS_BRANCH = "master" &&
    test $TRAVIS_PULL_REQUEST = "false" &&
    bash <(curl -s https://codecov.io/bash)
notifications:
  email: false
