name: TinySwift

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install pod
      run: cd Example ; pod install ; cd ..
    - name: Test
      run: xcodebuild test -workspace 'Example/TinySwift.xcworkspace' -scheme 'TinySwift-Example' -destination 'platform=iOS Simulator,name=iPhone 14 Pro'
    - name: Validate
      run: pod lib lint --allow-warnings
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      if: github.ref == 'refs/heads/master'
